version: '3.8'

services:
  # Frontend
  army-cop-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://army-cop-backend:8080/api
      - NEXT_PUBLIC_WS_URL=ws://army-cop-backend:8080/ws
    depends_on:
      - army-cop-backend
    networks:
      - army-cop-network
    restart: unless-stopped

  # Backend Services
  army-cop-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker,production
      - DATABASE_URL=jdbc:postgresql://postgres:5432/army_cop_db
      - DATABASE_USERNAME=army_cop_user
      - DATABASE_PASSWORD=secure_password_2024
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=army-cop
      - KEYCLOAK_CLIENT_ID=army-cop-backend
      - KEYCLOAK_CLIENT_SECRET=your-client-secret
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - keycloak
      - redis
    networks:
      - army-cop-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Database
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_DB=army_cop_db
      - POSTGRES_USER=army_cop_user
      - POSTGRES_PASSWORD=secure_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - army-cop-network
    restart: unless-stopped

  # Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin_password_2024
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres:5432/keycloak_db
      - KC_DB_USERNAME=keycloak_user
      - KC_DB_PASSWORD=keycloak_password_2024
      - KC_HOSTNAME_STRICT=false
      - KC_HTTP_ENABLED=true
    command: start-dev --import-realm
    volumes:
      - ./backend/keycloak:/opt/keycloak/data/import
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    networks:
      - army-cop-network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - army-cop-network
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - army-cop-frontend
      - army-cop-backend
    networks:
      - army-cop-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  army-cop-network:
    driver: bridge
