version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: army_cop_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d army_cop_test"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/army_cop_test
      KC_DB_USERNAME: test
      KC_DB_PASSWORD: test
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: start-dev --import-realm
    volumes:
      - ./keycloak/army-cop-realm.json:/opt/keycloak/data/import/army-cop-realm.json
